name: allegro_sim
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch=1.8.1
  - torchvision=0.9.1
  - cudatoolkit=11.1
  - pyyaml=6.0
  - einops=0.4.1
  - pip:
      - black
      - isort
      - pandas
      - seaborn
      - termcolor
      - timm
      - opencv-python
      - omegaconf
      - h5py
      - ikpy
      - wandb
      - hydra-core
      - ipdb
      - scipy>=1.5.0
      - tensorboard>=2.2.1
      - scikit-image
      - POT
      - info-nce-pytorch
      - blosc
      - scikit-learn
      - rospkg
